import 'package:validador_sigue/src/domain/entitites/modelo_validacion.dart';

class CajaDomiciliaria extends ModeloValidacion {
  CajaDomiciliaria({
    required super.entidadSigue,
    required super.dominiosCampos,
    required super.camposNoNulos,
    required super.validacionesPersonalizadas,
    required super.camposNulos,
  });

  static CajaDomiciliaria parametrosValidaciones() {
    return CajaDomiciliaria(
      entidadSigue: 'Nodo Alcantarillado Caja Domiciliaria',
      dominiosCampos: {
        'SUBTIPO': 'DomSubtip_CajaDomiciliaria',
        'ESTADOENRED': 'DomEstadoRedAlc',
        'MATERIAL': 'DomMaterNodAlc',
        'CALIDADDATO': 'DomCalidadDatoAlc',
        'SISTEMA': 'DomTipoSistAlc',
      },
      camposNoNulos: [
        "IDENTIFIC",
        "NORTE",
        "ESTE",
        "FECHADATO",
        "LOCALIZACI",
        "C_RASANTE",
        "C_TERRENO",
        "C_FONDO",
        "CONTRATO_I",
        "FECHA_INSP",
        "DIRECCION",
        "NDISENO",
      ],
      camposNulos: [
        "TIPO_ALIVI",
        "TIPO_VALV_",
        "NOMBRE",
        "PROFUNDIDA",
        "CONOREDUCC",
        "MATERCONO",
        "TIPO_CONO",
        "EST_CONO",
        "INICIAL_CU",
        "CAMARASIF",
        "EST_FISICO",
        "CABEZAL",
        "EST_TAPA",
        "EST_POZO",
        "MATESCALO",
        "ESTESCALON",
        "ESTCARGUE",
        "ESTCILIND",
        "ESTCANUE",
        "ESTOPERA",
        "CONTINSPE",
        "TIPOINSPEC",
        "TIPOALMAC",
        "COTACRESTA",
        "C_TECHO_VE",
        "LONGVERT",
        "LARGO",
        "ANCHO",
        "ALTO",
        "Q_BOMBEO",
        "TIPOBOMB",
        "UNIDBOMBEO",
        "HBOMBEO",
        "COTABOMBE",
        "VOLBOMBEO",
        "ESTREJILLA",
        "MATREJILLA",
        "TAMREJILLA",
        "ORIGENSEC",
        "DISTORIGEN",
        "ABSCISA",
      ],
      validacionesPersonalizadas: ['DIAMETRO1 <> DIAMETRO2'],
    );
  }
}
