import 'package:validador_sigue/src/domain/entitites/modelo_validacion.dart';

class Pozo extends ModeloValidacion {
  Pozo({
    required super.entidadSigue,
    required super.dominiosCampos,
    required super.camposNoNulos,
    required super.validacionesPersonalizadas,
    required super.camposNulos,
  });

  static Pozo parametrosValidaciones() {
    return Pozo(
      entidadSigue: 'Nodo Alcantarillado - Pozo',
      dominiosCampos: {
        'SUBTIPO': 'DomSubtip_Pozo',
        'ESTADOENRED': 'DomEstadoRedAlc',
        'MATERIAL': 'DomMaterNodAlc',
        'CALIDADDATO': 'DomCalidadDatoAlc',
        'SISTEMA': 'DomTipoSistAlc',
        'CONOREDUCC': 'DomVerifAlc',
        'MATERCONO': 'DomMateConoRed',
        'TIPO_CONO': 'DomTipoConoRed',
        'EST_CONO': 'DomEstadoCono',
        'INICIAL_CUENCAS': 'DomVerifAlc',
        'CAMARASIF': 'DomCamaraSifon',
        'EST_FISICO': 'DomEstadoFisAlc',
        'EST_TAPA': 'DomEstadoTapa',
        'EST_POZO': 'DomEstadoPozo',
        'MATESCALO': 'DomMateEscalo',
        'ESTCARGUE': 'DomEstadoCargue',
        'ESTCILIND': 'DomEstadoCilind',
        'ESTCANUE': 'DomEstadoCanuel',
        'ESTOPERA': 'DomEstadoOper',
        'TIPOINSPEC': 'DomTipoInspecc',
        'TIPOALMAC': 'DomTipoAlmac',
      },
      camposNoNulos: [
        "CLASE",
        "IDENTIFIC",
        "NORTE",
        "ESTE",
        "FECHADATO",
        "C_RASANTE",
        "C_TERRENO",
        "C_FONDO",
        "CONTRATO_ID",
        "PROFUNDIDA",
        "FECHA_INSP",
        "DIRECCION",
        "NDISENO",
      ],
      camposNulos: [
        "TIPO_ALIVIO",
        "TIPO_VALV_ANT",
        "LOCALIZACIONRELATIVA",
        "NOMBRE",
        "ROTACION",
        "CABEZAL",
        "COTACRESTA",
        "C_TECHO_VE",
        "LONGVERT",
        "LARGO",
        "ANCHO",
        "ALTO",
        "Q_BOMBEO",
        "TIPOBOMB",
        "UNIDBOMBEO",
        "HBOMBEO",
        "COTABOMBE",
        "VOLBOMBEO",
        "ESTREJILLA",
        "MATREJILLA",
        "TAMREJILLA",
        "ORIGENSEC",
        "DISTORIGEN",
        "ABSCISA",
      ],
      validacionesPersonalizadas: [],
    );
  }
}
