import 'package:validador_sigue/src/domain/entitites/modelo_validacion.dart';

class Secciontransversal extends ModeloValidacion {
  Secciontransversal({
    required super.entidadSigue,
    required super.dominiosCampos,
    required super.camposNoNulos,
    required super.validacionesPersonalizadas,
    required super.camposNulos,
  });

  static Secciontransversal parametrosValidaciones() {
    return Secciontransversal(
      entidadSigue: 'Nodo Alcantarillado Sección Transversal',
      dominiosCampos: {
        'CALIDADDATO': 'DomCalidadDatoAlc',
        'ORIGENSEC': 'DomOrigenSecc',
      },
      camposNoNulos: [
        "IDENTIFIC",
        "NORTE",
        "ESTE",
        "NOMBRE",
        "DISTORIGEN",
        "ABSCISA",
        "NDISENO",
      ],
      camposNulos: [
        "SUBTIPO",
        "FECHADATO",
        "TIPO_ALIVI",
        "TIPO_VALV_",
        "ESTADOENRE",
        "LOCALIZACIONRELATIVA",
        "C_RASANTE",
        "C_RASANTE",
        "C_TERRENO",
        "C_FONDO",
        "MATERIAL",
        "SISTEMA",
        "CONTRATO_ID",
        "PROFUNDIDAD",
        "CONOREDUCC",
        "MATERCONO",
        "MATERCONO",
        "TIPO_CONO",
        "EST_CONO",
        "INICIAL_CU",
        "ROTACION",
        "CAMARASIF",
        "EST_FISICO",
        "CABEZAL",
        "EST_TAPA",
        "EST_POZO",
        "MATESALO",
        "ESTESCALON",
        "ESTCARGUE",
        "ESTCILIND",
        "ESTCANUE",
        "ESTOPERA",
        "CONTINSPE",
        "FECHA_INSP",
        "TIPOINSPEC",
        "TIPOALMAC",
        "COTACRESTA",
        "C_TECHO_VE",
        "LONGVERT",
        "LARGO",
        "ANCHO",
        "ALTO",
        "Q_BOMBEO",
        "TIPOBOMB",
        "UNIDBOMBEO",
        "HBOMBEO",
        "COTABOMBE",
        "VOLBOMBEO",
        "DIRECCION",
        "ESTREJILLA",
        "MATREJILLA",
        "TAMREJILLA",
      ],
      validacionesPersonalizadas: [],
    );
  }
}
