import 'package:validador_sigue/src/domain/entitites/modelo_validacion.dart';

class AccesorioOtros extends ModeloValidacion {
  AccesorioOtros({
    required super.entidadSigue,
    required super.dominiosCampos,
    required super.camposNoNulos,
    required super.validacionesPersonalizadas,
    required super.camposNulos,
  });

  static AccesorioOtros parametrosValidaciones() {
    return AccesorioOtros(
      entidadSigue: 'Nodo Acueducto Entidad SIGUE',
      dominiosCampos: {
        'SUBTIPO': 'Dom_Subtip_AccesTapon',
        'ESTADOENRED': 'Dom_EstadoRed',
        'CALIDADDATO': 'Dom_CalidadDato',
        'MATERIAL': 'Dom_Material_Acue',
        'DIAMETRO1': 'Dom_DiamNom_Acue',
        'DIAMETRO2': 'Dom_DiamNom_Acue',
        'CLASEACCES': 'Dom_ClaseAccTapon',
      },
      camposNoNulos: [
        "IDENTIFIC",
        "NORTE",
        "ESTE",
        "FECHAINST",
        "LOCALIZACI",
        "ROTACION",
        "C_RASANTE",
        "PROFUN",
        "CONTRATO_I",
        "NDISENO",
      ],
      camposNulos: [
        "TIPOESPPUB",
        "MATESPPUBL",
        "AUTOMATIZA",
        "SENTIDOOPE",
        "ESTADOOPER",
        "TIPOOPERAC",
        "ESTADOFIS_",
        "TIPOVALVUL",
        "VUELTASCIE",
        "ESTADOFISI",
        "MARCA",
        "FUNCIONPIL",
        "ESTADOMED",
        "SECTORENTR",
        "SECTORSALI",
        "IDTUBERIAM",
        "CAUDAL_PRO",
        "TIPO_M",
        "FECHA_TOMA",
        "UBICACCAJI",
        "CENTRO",
        "L_ALM",
        "AREARESP",
        "TIPO_MUEST",
        "FUENTEABAS",
        "UBICAC_MUE",
        "PTOANALISI",
        "LOCPUNTO",
        "ESTADO",
        "FECHAESTAD",
        "CLASEPUNTO",
        "NROFILTROS",
        "NROSEDIMEN",
        "NROCOMPART",
        "NROMEZCLAR",
        "NROFLOCULA",
        "CAPACINSTA",
        "NROBOMBAS",
        "CAPABOMBEO",
        "COTABOMBEO",
        "ALTURADINA",
        "COTAFONDO",
        "COTAREBOSE",
        "CAPACIDAD",
        "NIVELMAXIM",
        "NIVELMINIM",
        "AREATRANSV",
        "TIENEVIGIL",
        "OPERACTANQ",
        "TIPOACCESO",
        "DIAMETROAC",
        "NOMBRE",
        "DIRECCION",
        "PRESION",
        "FECHA_TOMA",
      ],
      validacionesPersonalizadas: ['DIAMETRO1 <> DIAMETRO2'],
    );
  }
}
