import 'package:validador_sigue/src/domain/entitites/modelo_validacion.dart';

class CamaraAcceso extends ModeloValidacion {
  CamaraAcceso({
    required super.entidadSigue,
    required super.dominiosCampos,
    required super.camposNoNulos,
    required super.validacionesPersonalizadas,
    required super.camposNulos,
  });

  static CamaraAcceso parametrosValidaciones() {
    return CamaraAcceso(
      entidadSigue: 'Nodo Acueducto Camara de Acceso',
      dominiosCampos: {
        'SUBTIPO': 'Dom_Subtip_AccesUnion',
        'ESTADOENRED': 'Dom_EstadoRed',
        'CALIDADDATO': 'Dom_CalidadDato',
        'MATERIAL': 'Dom_Material_Acue',
        'DIAMETRO1': 'Dom_DiamNom_Acue',
        'DIAMETRO2': 'Dom_DiamNom_Acue',
        'CLASEACCES': 'Dom_ClaseAccUnion',
        'ESTADOFISICOH': 'Dom_EstadoFisHidrante',
      },
      camposNoNulos: [
        "IDENTIFIC",
        "NORTE",
        "ESTE",
        "FECHAINST",
        "LOCALIZACIONRELATIVA",
        "ROTACION",
        "C_RASANTE",
        "PROFUN",
        "CONTRATO_ID",
        "DIAMETROAC",
        "NDISENO",
        "DIRECCION",
      ],
      camposNulos: [
        "MATERIAL",
        "TIPOESPPUB",
        "MATESPPUBL",
        "AUTOMATIZA",
        "DIAMETRO1",
        "DIAMETRO2",
        "SENTIDOOPERAC",
        "ESTADOOPERAC",
        "TIPOOPERAC",
        "ESTADOFIS_VAL",
        "TIPOVALVUL",
        "VUELTASCIE",
        "CLASEACCES",
        "ESTADOFISICOH",
        "MARCA",
        "FUNCIONPIL",
        "ESTADOMED",
        "SECTORENTR",
        "SECTORSALI",
        "IDTUBERIAMEDIDA",
        "CAUDAL_PROMEDIO",
        "TIPO_M",
        "FECHA_TOMA_C",
        "UBICACCAJI",
        "CENTRO",
        "L_ALM",
        "AREARESP",
        "TIPO_MUESTR",
        "FUENTEABAS",
        "UBICAC_MUES",
        "PTOANALISI",
        "LOCPUNTO",
        "ESTADO",
        "FECHAESTADO",
        "CLASEPUNTO",
        "NROFILTROS",
        "NROSEDIMEN",
        "NROCOMPART",
        "NROMEZCLAR",
        "NROFLOCULA",
        "CAPACINSTA",
        "NROBOMBAS",
        "CAPABOMBEO",
        "COTABOMBEO",
        "ALTURADINA",
        "COTAFONDO",
        "COTAREBOSE",
        "CAPACIDAD",
        "NIVELMAXIM",
        "NIVELMINIM",
        "AREATRANSV",
        "TIENEVIGIL",
        "OPERACTANQ",
        "PRESION",
      ],
      validacionesPersonalizadas: [],
    );
  }
}
