import 'package:validador_sigue/src/domain/entitites/modelo_validacion.dart';

class PilaMuestreo extends ModeloValidacion {
  PilaMuestreo({
    required super.entidadSigue,
    required super.dominiosCampos,
    required super.camposNoNulos,
    required super.validacionesPersonalizadas,
    required super.camposNulos,
  });

  static PilaMuestreo parametrosValidaciones() {
    return PilaMuestreo(
      entidadSigue: 'Nodo Acueducto Pila Muestreo',
      dominiosCampos: {
        'SUBTIPO': 'Dom_Subtip_PilaMuest',
        'ESTADOENRED': 'Dom_EstadoRed',
        'CALIDADDATO': 'Dom_CalidadDato',
        'MATERIAL': 'Dom_Material_Acue',
        'TIPOESPPUB': 'Dom_TipoEspPub',
        'DIAMETRO1': 'Dom_DiamNom_Acue',
        'TIPO_MUESTR': 'dom_tipo_muestra',
        'FUENTEABAS': 'Dom_FuenteAbastec',
        'UBICAC_MUES': 'dom_ubicacion_muestra',
        'PTOANALISI': 'Dom_PtoAnalisis',
        'LOCPUNTO': 'Dom_LocPto',
        'ESTADO': 'Dom_EstadoPtoMuestreo',
        'CLASEPUNTO': 'Dom_ClasePtoMuest',
      },
      camposNoNulos: [
        "IDENTIFIC",
        "NORTE",
        "ESTE",
        "FECHAINST",
        "LOCALIZACIONRELATIVA",
        "ROTACION",
        "C_RASANTE",
        "CONTRATO_ID",
        "CENTRO",
        "L_ALM",
        "AREARESP",
        "FECHAESTADO",
        "DIRECCION",
        "NDISENO",
      ],
      camposNulos: [
        "AUTOMATIZA",
        "DIAMETRO2",
        "SENTIDOOPERAC",
        "ESTADOOPERAC",
        "TIPOOPERAC",
        "ESTADOFIS_VAL",
        "TIPOVALVUL",
        "VUELTASCIE",
        "CLASEACCES",
        "ESTADOFISICOH",
        "MARCA",
        "FUNCIONPIL",
        "ESTADOMED",
        "SECTORENTR",
        "SECTORSALI",
        "IDTUBERIAMEDIDA",
        "CAUDAL_PROMEDIO",
        "TIPO_M",
        "FECHA_TOMA_C",
        "UBICACCAJI",
        "NROFILTROS",
        "NROSEDIMEN",
        "NROCOMPART",
        "NROMEZCLAR",
        "NROFLOCULA",
        "CAPACINSTA",
        "NROBOMBAS",
        "CAPABOMBEO",
        "COTABOMBEO",
        "ALTURADINA",
        "COTAFONDO",
        "COTAREBOSE",
        "CAPACIDAD",
        "NIVELMAXIM",
        "NIVELMINIM",
        "AREATRANSV",
        "TIENEVIGIL",
        "OPERACTANQ",
        "TIPOACCESO",
        "DIAMETROAC",
        "PRESION",
      ],
      validacionesPersonalizadas: [],
    );
  }
}
