import 'package:validador_sigue/src/domain/entitites/modelo_validacion.dart';

class Tanque extends ModeloValidacion {
  Tanque({
    required super.dominiosCampos,
    required super.camposNoNulos,
    required super.validacionesPersonalizadas,
    required super.camposNulos,
  });

  static Tanque parametrosValidaciones() {
    return Tanque(
      dominiosCampos: {
        'SUBTIPO': 'Dom_Subtip_Tanque',
        'ESTADOENRED': 'Dom_EstadoRed',
        'CALIDADDATO': 'Dom_CalidadDato',
        'TIENEVIGIL': 'dom_tiene_vigilancia',
        'OPERACTANQ': 'Dom_OperacTanque',
      },
      camposNoNulos: [
        "IDENTIFIC",
        "NORTE",
        "ESTE",
        "FECHAINST",
        "LOCALIZACI",
        "ROTACION",
        "C_RASANTE",
        "CONTRATO_I",
        "COTAFONDO",
        "COTAREBOSE",
        "CAPACIDAD",
        "NIVELMAXIM",
        "NIVELMINIM",
        "AREATRANSV",
        "DIRECCION",
        "NDISENO",
      ],
      camposNulos: [
        "PROFUN",
        "MATERIAL",
        "TIPOESPPUB",
        "MATESPPUBL",
        "AUTOMATIZA",
        "DIAMETRO1",
        "DIAMETRO2",
        "SENTIDOOPE",
        "ESTADOOPER",
        "TIPOOPERAC",
        "ESTADOFIS_",
        "TIPOVALVUL",
        "VUELTASCIE",
        "CLASEACCES",
        "ESTADOFISI",
        "MARCA",
        "FUNCIONPIL",
        "ESTADOMED",
        "SECTORENTR",
        "SECTORSALI",
        "IDTUBERIAM",
        "CAUDAL_PRO",
        "TIPO_M",
        "FECHA_TOMA",
        "UBICACCAJI",
        "CENTRO",
        "L_ALM",
        "AREARESP",
        "TIPO_MUEST",
        "FUENTEABAS",
        "UBICAC_MUE",
        "PTOANALISI",
        "LOCPUNTO",
        "ESTADO",
        "FECHAESTAD",
        "CLASEPUNTO",
        "NROFILTROS",
        "NROSEDIMEN",
        "NROCOMPART",
        "NROMEZCLAR",
        "NROFLOCULA",
        "CAPACINSTA",
        "NROBOMBAS",
        "CAPABOMBEO",
        "COTABOMBEO",
        "ALTURADINA",
        "TIPOACCESO",
        "DIAMETROAC",
        "PRESION",
      ],
      validacionesPersonalizadas: [],
    );
  }
}
