import 'package:validador_sigue/src/domain/entitites/modelo_validacion.dart';

class ValvulaSistema extends ModeloValidacion {
  ValvulaSistema({
    required super.entidadSigue,
    required super.dominiosCampos,
    required super.camposNoNulos,
    required super.validacionesPersonalizadas,
    required super.camposNulos,
  });

  static ValvulaSistema parametrosValidaciones() {
    return ValvulaSistema(
      entidadSigue: 'Nodo Acueducto Valvula Sistema',
      dominiosCampos: {
        'SUBTIPO': 'Dom_Subtip_ValvControl',
        'ESTADOENRED': 'Dom_EstadoRed',
        'CALIDADDATO': 'Dom_CalidadDato',
        'MATERIAL': 'Dom_Material_Acue',
        'TIPOESPPUB': 'Dom_TipoEspPub',
        'MATESPPUBL': 'Dom_MatEspPublic',
        'AUTOMATIZA': 'Dom_Verificacion_acue',
        'DIAMETRO1': 'Dom_DiamNom_Acue',
        'SENTIDOOPERAC': 'Dom_Sentido_Operacion',
        'ESTADOOPERAC': 'Dom_Estado_Operacion',
        'TIPOOPERAC': 'Dom_TipoOperac',
        'ESTADOFIS_VAL': 'Dom_EstadoFisVal',
        'TIPOVALVUL': 'Dom_TipoValvula',
      },
      camposNoNulos: [
        "IDENTIFIC",
        "NORTE",
        "ESTE",
        "FECHAINST",
        "LOCALIZACIONRELATIVA",
        "ROTACION",
        "C_RASANTE",
        "PROFUN",
        "CONTRATO_I",
        "VUELTASCIE",
        "DIRECCION",
        "NDISENO",
      ],
      camposNulos: [
        "DIAMETRO2",
        "CLASEACCES",
        "ESTADOFISI",
        "MARCA",
        "FUNCIONPIL",
        "ESTADOMED",
        "SECTORENTR",
        "SECTORSALI",
        "IDTUBERIAM",
        "CAUDAL_PRO",
        "TIPO_M",
        "FECHA_TOMA",
        "UBICACCAJI",
        "CENTRO",
        "L_ALM",
        "AREARESP",
        "TIPO_MUEST",
        "FUENTEABAS",
        "UBICAC_MUE",
        "PTOANALISI",
        "LOCPUNTO",
        "ESTADO",
        "FECHAESTAD",
        "CLASEPUNTO",
        "NROFILTROS",
        "NROSEDIMEN",
        "NROCOMPART",
        "NROMEZCLAR",
        "NROFLOCULA",
        "CAPACINSTA",
        "NROBOMBAS",
        "CAPABOMBEO",
        "COTABOMBEO",
        "ALTURADINA",
        "COTAFONDO",
        "COTAREBOSE",
        "CAPACIDAD",
        "NIVELMAXIM",
        "NIVELMINIM",
        "AREATRANSV",
        "TIENEVIGIL",
        "OPERACTANQ",
        "TIPOACCESO",
        "DIAMETROAC",
        "NOMBRE",
        "PRESION",
        "FECHA_TOMA",
      ],
      validacionesPersonalizadas: [],
    );
  }
}
