-- CARGANDO EXTENSIONES
INSTALL SPATIAL;
LOAD SPATIAL;

/*
 * ACUEDUCTO NODOS
 * */

--TABLA BASE RECORD NODOS ACUEDUCTO
CREATE OR REPLACE TABLE record.model_nodos_acueducto as
select * from record.gdb_nodo_acueducto;

-- MACRO PARA CARGAR NODOS RECORD ACUEDUCTO SHAPE
PREPARE cargar_nodos_acueducto_shp AS
INSERT INTO record.model_nodos_acueducto
(CLASE, SUBTIPO, IDENTIFIC, NORTE, ESTE, FECHAINST, ESTADOENRED, 
LOCALIZACIONRELATIVA, CALIDADDATO, ROTACION, C_RASANTE, PROFUN, MATERIAL, 
VINCULO, OBSERVACIONES, CONTRATO_ID, NDISENO, TIPOESPPUB, MATESPPUBL, 
AUTOMATIZA, DIAMETRO1, DIAMETRO2, SENTIDOOPERAC, ESTADOOPERAC, TIPOOPERAC, 
ESTADOFIS_VAL, TIPOVALVUL, VUELTASCIE, CLASEACCES, ESTADOFISICOH, MARCA, 
FUNCIONPIL, ESTADOMED, SECTORENTR, SECTORSALI, IDTUBERIAMEDIDA, CAUDAL_PROMEDIO, 
TIPO_M, FECHA_TOMA_C, UBICACCAJI, CENTRO, L_ALM, AREARESP, TIPO_MUESTR, FUENTEABAS, 
UBICAC_MUES, PTOANALISI, LOCPUNTO, ESTADO, FECHAESTADO, CLASEPUNTO, NROFILTROS, NROSEDIMEN, 
NROCOMPART, NROMEZCLAR, NROFLOCULA, CAPACINSTA, NROBOMBAS, CAPABOMBEO, COTABOMBEO, ALTURADINA, 
COTAFONDO, COTAREBOSE, CAPACIDAD, NIVELMAXIM, NIVELMINIM, AREATRANSV, TIENEVIGIL, OPERACTANQ, 
TIPOACCESO, DIAMETROAC, NOMBRE, DIRECCION, PRESION, CODACTIVO_FIJO, Shape)
SELECT  
CLASE, SUBTIPO, IDENTIFIC, NORTE, ESTE, FECHAINST, ESTADOENRE, 
LOCALIZACI, CALIDADDAT, ROTACION, C_RASANTE, PROFUN, MATERIAL, 
VINCULO, OBSERVACIO, CONTRATO_I, NDISENO, TIPOESPPUB, MATESPPUBL, 
AUTOMATIZA, DIAMETRO1, DIAMETRO2, SENTIDOOPE, ESTADOOPER, TIPOOPERAC, 
ESTADOFIS_, TIPOVALVUL, VUELTASCIE, CLASEACCES, ESTADOFISI, MARCA, 
FUNCIONPIL, ESTADOMED, SECTORENTR, SECTORSALI, IDTUBERIAM, CAUDAL_PRO, 
TIPO_M, FECHA_TOMA, UBICACCAJI, CENTRO, L_ALM, AREARESP, TIPO_MUEST, FUENTEABAS, 
UBICAC_MUE, PTOANALISI, LOCPUNTO, ESTADO, FECHAESTAD, CLASEPUNTO, NROFILTROS, NROSEDIMEN, 
NROCOMPART, NROMEZCLAR, NROFLOCULA, CAPACINSTA, NROBOMBAS, CAPABOMBEO, COTABOMBEO, ALTURADINA, 
COTAFONDO, COTAREBOSE, CAPACIDAD, NIVELMAXIM, NIVELMINIM, AREATRANSV, TIENEVIGIL, OPERACTANQ, 
TIPOACCESO, DIAMETROAC, NOMBRE, DIRECCION, PRESION, CODACTIVO_, geom
FROM st_read(?);

-- MACRO PARA CARGAR NODOS ACUEDUCTO GDB
PREPARE cargar_nodos_acueducto_gdb AS
INSERT INTO record.model_nodos_acueducto
(CLASE, SUBTIPO, IDENTIFIC, NORTE, ESTE, FECHAINST, ESTADOENRED, 
LOCALIZACIONRELATIVA, CALIDADDATO, ROTACION, C_RASANTE, PROFUN, MATERIAL, 
VINCULO, OBSERVACIONES, CONTRATO_ID, NDISENO, TIPOESPPUB, MATESPPUBL, 
AUTOMATIZA, DIAMETRO1, DIAMETRO2, SENTIDOOPERAC, ESTADOOPERAC, TIPOOPERAC, 
ESTADOFIS_VAL, TIPOVALVUL, VUELTASCIE, CLASEACCES, ESTADOFISICOH, MARCA, 
FUNCIONPIL, ESTADOMED, SECTORENTR, SECTORSALI, IDTUBERIAMEDIDA, CAUDAL_PROMEDIO, 
TIPO_M, FECHA_TOMA_C, UBICACCAJI, CENTRO, L_ALM, AREARESP, TIPO_MUESTR, FUENTEABAS, 
UBICAC_MUES, PTOANALISI, LOCPUNTO, ESTADO, FECHAESTADO, CLASEPUNTO, NROFILTROS, NROSEDIMEN, 
NROCOMPART, NROMEZCLAR, NROFLOCULA, CAPACINSTA, NROBOMBAS, CAPABOMBEO, COTABOMBEO, ALTURADINA, 
COTAFONDO, COTAREBOSE, CAPACIDAD, NIVELMAXIM, NIVELMINIM, AREATRANSV, TIENEVIGIL, OPERACTANQ, 
TIPOACCESO, DIAMETROAC, NOMBRE, DIRECCION, PRESION, CODACTIVO_FIJO, Shape)
SELECT  
CLASE, SUBTIPO, IDENTIFIC, NORTE, ESTE, FECHAINST, ESTADOENRED, 
LOCALIZACIONRELATIVA, CALIDADDATO, ROTACION, C_RASANTE, PROFUN, MATERIAL, 
VINCULO, OBSERVACIONES, CONTRATO_ID, NDISENO, TIPOESPPUB, MATESPPUBL, 
AUTOMATIZA, DIAMETRO1, DIAMETRO2, SENTIDOOPERAC, ESTADOOPERAC, TIPOOPERAC, 
ESTADOFIS_VAL, TIPOVALVUL, VUELTASCIE, CLASEACCES, ESTADOFISICOH, MARCA, 
FUNCIONPIL, ESTADOMED, SECTORENTR, SECTORSALI, IDTUBERIAMEDIDA, CAUDAL_PROMEDIO, 
TIPO_M, FECHA_TOMA_C, UBICACCAJI, CENTRO, L_ALM, AREARESP, TIPO_MUESTR, FUENTEABAS, 
UBICAC_MUES, PTOANALISI, LOCPUNTO, ESTADO, FECHAESTADO, CLASEPUNTO, NROFILTROS, NROSEDIMEN, 
NROCOMPART, NROMEZCLAR, NROFLOCULA, CAPACINSTA, NROBOMBAS, CAPABOMBEO, COTABOMBEO, ALTURADINA, 
COTAFONDO, COTAREBOSE, CAPACIDAD, NIVELMAXIM, NIVELMINIM, AREATRANSV, TIENEVIGIL, OPERACTANQ, 
TIPOACCESO, DIAMETROAC, NOMBRE, DIRECCION, PRESION, CODACTIVO_FIJO, Shape
FROM st_read(?,layer=?);


/*
 * ACUEDUCTO LÍNEAS
 * */

--TABLA BASE RECORD LINEAS ACUEDUCTO
CREATE OR REPLACE TABLE record.model_lineas_acueducto as
select * from record.gdb_lineas_acueducto;

-- MACRO PARA CARGAR NODOS RECORD ACUEDUCTO SHAPE
PREPARE cargar_lineas_acueducto_shp AS
INSERT INTO record.model_lineas_acueducto
(CLASE, SUBTIPO, N_INICIAL, N_FINAL, FECHAINST, ESTADOENRED, DIAMETRO, 
MATERIAL, CALIDADDEDATO, ESTADOLEGAL, OBSERV, TIPOINSTALACION, 
CONTRATO_ID, NDISENO, NOMBRE, COSTADO, T_SECCION, AREA_TR_M2, 
C_RASANTEI, C_RASANTEF, C_CLAVEI, C_CLAVEF, PROFUNDIDAD, 
RUGOSIDAD, LONGITUD_m, CODACTIVO_FIJO, Shape_Length, Shape)
SELECT 
CLASE, SUBTIPO, N_INICIAL, N_FINAL, FECHAINST, ESTADOENRE, DIAMETRO, 
MATERIAL, CALIDADDED, ESTADOLEGA, OBSERV, TIPOINSTAL, 
CONTRATO_I, NDISENO, NOMBRE, COSTADO, T_SECCION, AREA_TR_M2, 
C_RASANTEI, C_RASANTEF, C_CLAVEI, C_CLAVEF, PROFUNDIDA, 
RUGOSIDAD, LONGITUD_m, CODACTIVO_, Shape_Leng, geom
FROM st_read(?);

-- MACRO PARA CARGAR LINEAS RECORD ACUEDUCTO GDB
PREPARE cargar_lineas_acueducto_gdb AS
INSERT INTO record.model_lineas_acueducto
(CLASE, SUBTIPO, N_INICIAL, N_FINAL, FECHAINST, ESTADOENRED, DIAMETRO, 
MATERIAL, CALIDADDEDATO, ESTADOLEGAL, OBSERV, TIPOINSTALACION, 
CONTRATO_ID, NDISENO, NOMBRE, COSTADO, T_SECCION, AREA_TR_M2, 
C_RASANTEI, C_RASANTEF, C_CLAVEI, C_CLAVEF, PROFUNDIDAD, 
RUGOSIDAD, LONGITUD_m, CODACTIVO_FIJO, Shape_Length, Shape)
SELECT 
CLASE, SUBTIPO, N_INICIAL, N_FINAL, FECHAINST, ESTADOENRED, DIAMETRO, 
MATERIAL, CALIDADDEDATO, ESTADOLEGAL, OBSERV, TIPOINSTALACION, 
CONTRATO_ID, NDISENO, NOMBRE, COSTADO, T_SECCION, AREA_TR_M2, 
C_RASANTEI, C_RASANTEF, C_CLAVEI, C_CLAVEF, PROFUNDIDAD, 
RUGOSIDAD, LONGITUD_m, CODACTIVO_FIJO, Shape_Length, Shape
FROM st_read(?,layer=?);


/*
 * ALCANTARILLADO LÍNEAS
 * */

CREATE OR REPLACE TABLE record.model_lineas_alcantarillado as
select * from record.gdb_linea_alcantarillado;

-- MACRO PARA CARGAR LINEAS ALCANTARILLADO SHP
PREPARE cargar_lineas_alcantarillado_shp AS
INSERT INTO record.model_lineas_alcantarillado
(CLASE, SUBTIPO, N_INICIAL, N_FINAL, SISTEMA, FECHAINST, ESTADOENRED, 
MATERIAL, MATERIAL2, CALIDADDATO, ESTADOLEGAL, OBSERVACIONES, CONTRATO_ID, 
NDISENO, DIAMETRO, T_SECCION, CAM_CAIDA, C_RASATEI, C_RASANTEF, C_CLAVEI, C_CLAVEF, 
C_BATEAI, C_BATEAF, PROFUNDIDAD, PENDIENTE, NOMBRE, NROCONDUCTOS, BASE, ALTURA1, ALTURA2, 
ANCHOBERMA, TALUD1, TALUD2, CODACTIVOS_FIJOS, LONGITUD_M, INSTALACI, MATESPPUBL, 
TIPOINSPEC, GRADOEST, GRADOOPER, RUGOSIDAD, SHAPE_Length, SHAPE)
SELECT 
CLASE, SUBTIPO, N_INICIAL, N_FINAL, SISTEMA, FECHAINST, ESTADOENRE, 
MATERIAL, MATERIAL2, CALIDADDAT, ESTADOLEGA, OBSERVACIO, CONTRATO_I, 
NDISENO, DIAMETRO, T_SECCION, CAM_CAIDA, C_RASATEI, C_RASANTEF, C_CLAVEI, C_CLAVEF, 
C_BATEAI, C_BATEAF, PROFUNDIDA, PENDIENTE, NOMBRE, NROCONDUCT, BASE, ALTURA1, ALTURA2, 
ANCHOBERMA, TALUD1, TALUD2, CODACTIVOS, LONGITUD_M, INSTALACI, MATESPPUBL, 
TIPOINSPEC, GRADOEST, GRADOOPER, RUGOSIDAD, SHAPE_Leng, geom
FROM ST_READ(?);

-- MACRO PARA CARGAR LINEAS ALCANTARILLADO GDB
PREPARE cargar_lineas_alcantarillado_gdb AS
INSERT INTO record.model_lineas_alcantarillado
(CLASE, SUBTIPO, N_INICIAL, N_FINAL, SISTEMA, FECHAINST, ESTADOENRED, 
MATERIAL, MATERIAL2, CALIDADDATO, ESTADOLEGAL, OBSERVACIONES, CONTRATO_ID, 
NDISENO, DIAMETRO, T_SECCION, CAM_CAIDA, C_RASATEI, C_RASANTEF, C_CLAVEI, C_CLAVEF, 
C_BATEAI, C_BATEAF, PROFUNDIDAD, PENDIENTE, NOMBRE, NROCONDUCTOS, BASE, ALTURA1, ALTURA2, 
ANCHOBERMA, TALUD1, TALUD2, CODACTIVOS_FIJOS, LONGITUD_M, INSTALACI, MATESPPUBL, 
TIPOINSPEC, GRADOEST, GRADOOPER, RUGOSIDAD, SHAPE_Length, SHAPE)
SELECT 
CLASE, SUBTIPO, N_INICIAL, N_FINAL, SISTEMA, FECHAINST, ESTADOENRED, 
MATERIAL, MATERIAL2, CALIDADDATO, ESTADOLEGAL, OBSERVACIONES, CONTRATO_ID, 
NDISENO, DIAMETRO, T_SECCION, CAM_CAIDA, C_RASATEI, C_RASANTEF, C_CLAVEI, C_CLAVEF, 
C_BATEAI, C_BATEAF, PROFUNDIDAD, PENDIENTE, NOMBRE, NROCONDUCTOS, BASE, ALTURA1, ALTURA2, 
ANCHOBERMA, TALUD1, TALUD2, CODACTIVOS_FIJOS, LONGITUD_M, INSTALACI, MATESPPUBL, 
TIPOINSPEC, GRADOEST, GRADOOPER, RUGOSIDAD, SHAPE_Length, SHAPE
FROM st_read(?,layer=?);


/*
 * ALCANTARILLADO NODOS
 * */

CREATE OR REPLACE TABLE record.model_nodos_alcantarillado as
select * from record.gdb_nodo_alcantarillado;

-- MACRO PARA CARGAR NODOS ALCANTARILLADO SHP
PREPARE cargar_nodos_alcantarillado_shp AS
INSERT INTO record.model_nodos_alcantarillado
(CLASE, SUBTIPO, IDENTIFIC, NORTE, ESTE, SISTEMA, FECHADATO, ESTADOENRED, 
LOCALIZACIONRELATIVA, C_RASANTE, C_TERRENO, C_FONDO, MATERIAL, CALIDADDATO, 
NOMBRE, OBSERV, CONTRATO_ID, NDISENO, PROFUNDIDA, CONOREDUCC, MATERCONO, 
TIPO_CONO, EST_CONO, INICIAL_CUENCAS, ROTACION, CAMARASIF, EST_FISICO, 
EST_TAPA, EST_POZO, MATESCALO, ESTESCALON, ESTCARGUE, ESTCILIND, ESTCANUE, 
ESTOPERA, CONTINSPE, FECHA_INSP, TIPOINSPEC, TIPOALMAC, MARGENDESC, 
TIPO_ALIVIO, TIPO_VALV_ANT, CABEZAL, COTACRESTA, C_TECHO_VE, LONGVERT, 
LARGO, ANCHO, ALTO, Q_BOMBEO, TIPOBOMB, UNIDBOMBEO, HBOMBEO, 
COTABOMBE, VOLBOMBEO, DIRECCION, ESTREJILLA, MATREJILLA, 
TAMREJILLA, ORIGENSEC, DISTORIGEN, ABSCISA, CODACTIVO_FIJO, SHAPE)
SELECT 
CLASE, SUBTIPO, IDENTIFIC, NORTE, ESTE, SISTEMA, FECHADATO, ESTADOENRE, 
LOCALIZACI, C_RASANTE, C_TERRENO, C_FONDO, MATERIAL, CALIDADDAT, 
NOMBRE, OBSERV, CONTRATO_I, NDISENO, PROFUNDIDA, CONOREDUCC, MATERCONO, 
TIPO_CONO, EST_CONO, INICIAL_CU, ROTACION, CAMARASIF, EST_FISICO, 
EST_TAPA, EST_POZO, MATESCALO, ESTESCALON, ESTCARGUE, ESTCILIND, ESTCANUE, 
ESTOPERA, CONTINSPE, FECHA_INSP, TIPOINSPEC, TIPOALMAC, MARGENDESC, 
TIPO_ALIVI, TIPO_VALV_, CABEZAL, COTACRESTA, C_TECHO_VE, LONGVERT, 
LARGO, ANCHO, ALTO, Q_BOMBEO, TIPOBOMB, UNIDBOMBEO, HBOMBEO, 
COTABOMBE, VOLBOMBEO, DIRECCION, ESTREJILLA, MATREJILLA, 
TAMREJILLA, ORIGENSEC, DISTORIGEN, ABSCISA, CODACTIVO_, geom
FROM ST_READ(?);


-- MACRO PARA CARGAR NODOS ALCANTARILLADO GDB
PREPARE cargar_nodos_alcantarillado_gdb AS
INSERT INTO record.model_nodos_alcantarillado
(CLASE, SUBTIPO, IDENTIFIC, NORTE, ESTE, SISTEMA, FECHADATO, ESTADOENRED, 
LOCALIZACIONRELATIVA, C_RASANTE, C_TERRENO, C_FONDO, MATERIAL, CALIDADDATO, 
NOMBRE, OBSERV, CONTRATO_ID, NDISENO, PROFUNDIDA, CONOREDUCC, MATERCONO, 
TIPO_CONO, EST_CONO, INICIAL_CUENCAS, ROTACION, CAMARASIF, EST_FISICO, 
EST_TAPA, EST_POZO, MATESCALO, ESTESCALON, ESTCARGUE, ESTCILIND, ESTCANUE, 
ESTOPERA, CONTINSPE, FECHA_INSP, TIPOINSPEC, TIPOALMAC, MARGENDESC, 
TIPO_ALIVIO, TIPO_VALV_ANT, CABEZAL, COTACRESTA, C_TECHO_VE, LONGVERT, 
LARGO, ANCHO, ALTO, Q_BOMBEO, TIPOBOMB, UNIDBOMBEO, HBOMBEO, 
COTABOMBE, VOLBOMBEO, DIRECCION, ESTREJILLA, MATREJILLA, 
TAMREJILLA, ORIGENSEC, DISTORIGEN, ABSCISA, CODACTIVO_FIJO, SHAPE)
SELECT 
CLASE, SUBTIPO, IDENTIFIC, NORTE, ESTE, SISTEMA, FECHADATO, ESTADOENRED, 
LOCALIZACIONRELATIVA, C_RASANTE, C_TERRENO, C_FONDO, MATERIAL, CALIDADDATO, 
NOMBRE, OBSERV, CONTRATO_ID, NDISENO, PROFUNDIDA, CONOREDUCC, MATERCONO, 
TIPO_CONO, EST_CONO, INICIAL_CUENCAS, ROTACION, CAMARASIF, EST_FISICO, 
EST_TAPA, EST_POZO, MATESCALO, ESTESCALON, ESTCARGUE, ESTCILIND, ESTCANUE, 
ESTOPERA, CONTINSPE, FECHA_INSP, TIPOINSPEC, TIPOALMAC, MARGENDESC, 
TIPO_ALIVIO, TIPO_VALV_ANT, CABEZAL, COTACRESTA, C_TECHO_VE, LONGVERT, 
LARGO, ANCHO, ALTO, Q_BOMBEO, TIPOBOMB, UNIDBOMBEO, HBOMBEO, 
COTABOMBE, VOLBOMBEO, DIRECCION, ESTREJILLA, MATREJILLA, 
TAMREJILLA, ORIGENSEC, DISTORIGEN, ABSCISA, CODACTIVO_FIJO, SHAPE
FROM ST_READ(?, layer=?);


/*
 * ALCANTARILLADO AREAS
 * */

CREATE OR REPLACE TABLE record.model_area_alcantarillado as
select * from record.gdb_area_alcantarillado;

-- MACRO PARA CARGAR AREAS ALCANTARILLADO SHP
PREPARE cargar_areas_alcantarillado_shp AS
INSERT INTO record.model_area_alcantarillado
(CLASE, IDENTIFIC, FECHADATO, CALIDADDATO, CONTRATO_ID, NDISENO, VOLUMEN_M3, 
RECUBRIMIE, PROFUND_M, CUBIERTA, ESNATURAL, W, PENDIENTE, 
IMPERMEABILIDAD, AREA, SHAPE_Length, SHAPE_Area, SHAPE)
SELECT 
CLASE, IDENTIFIC, FECHADATO, CALIDADDAT, CONTRATO_I, NDISENO, VOLUMEN_M3, 
RECUBRIMIE, PROFUND_M, CUBIERTA, ESNATURAL, W, PENDIENTE, 
IMPERMEABI, AREA, SHAPE_Leng, SHAPE_Area, geom
FROM ST_READ(?);

-- MACRO PARA CARGAR AREAS ALCANTARILLADO SHP
PREPARE cargar_areas_alcantarillado_gdb AS
INSERT INTO record.model_area_alcantarillado
(CLASE, IDENTIFIC, FECHADATO, CALIDADDATO, CONTRATO_ID, NDISENO, VOLUMEN_M3, 
RECUBRIMIE, PROFUND_M, CUBIERTA, ESNATURAL, W, PENDIENTE, 
IMPERMEABILIDAD, AREA, SHAPE_Length, SHAPE_Area, SHAPE)
SELECT 
CLASE, IDENTIFIC, FECHADATO, CALIDADDATO, CONTRATO_ID, NDISENO, VOLUMEN_M3, 
RECUBRIMIE, PROFUND_M, CUBIERTA, ESNATURAL, W, PENDIENTE, 
IMPERMEABILIDAD, AREA, SHAPE_Length, SHAPE_Area, SHAPE
FROM ST_READ(?, layer=?);
